# Topics - Numpy, Creating Arrays, Querying Dimensions,Array Properties and Operations, Functions, Manipulations, Broadcasting, Linear Algebra and Advanced Array Operations

## NumPy

NumPy (Numerical Python) is a library for the Python programming language that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [2]:
# To use numpy you need to install numpy library (if you don not have it in your system)
# you can do so by executing the below command

#pip install numpy

In [3]:
# To use NumPy in your Python program, you need to import it:
import numpy as np

## Arrays

* The core object in NumPy is the ndarray, which is a shorthand for "n-dimensional array".<br> 
* These arrays are faster and more efficient than Python lists for large datasets.



## Creating Arrays

You can create array in many ways

### Creating Arrays from `List`

In [4]:
arr = np.array([1,2,3,4,5])
print(f"Array from List: {arr}")

#From Nested Lists - 2d Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) 
print(f"Array 2d: {arr_2d}")

Array from List: [1 2 3 4 5]
Array 2d: [[1 2 3]
 [4 5 6]]


### Creating from `Built-in` functions

In [5]:
#From Built-in functions
zero = np.zeros((3, 3))        # Creates a 3x3 array filled with zeros
print(f"Array filled with zeros: {zero}")

ones = np.ones((2, 4))         # Creates a 2x4 array filled with ones
print(f"Array filled with ones: {ones}")

ex1 = np.arange(0, 10, 2)     # Creates an array with values from 0 to 10 with a step of 2
print(f"Array filled with values from 0 to 10 with step 2: {ex1}")

line = np.linspace(0, 1, 5)    # Creates an array with 5 values evenly spaced between 0 and 1
print(f"Array with 5 values evenly spaced between 0 and 1: {line}")

Array filled with zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array filled with ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array filled with values from 0 to 10 with step 2: [0 2 4 6 8]
Array with 5 values evenly spaced between 0 and 1: [0.   0.25 0.5  0.75 1.  ]


### Creating Arrays from `Random` function

In [35]:
# np.random.rand() Generates random numbers from a uniform distribution between 0 and 1.
random_array = np.random.rand(5) # Create a 1D array of 5 random numbers
print(f"1D array of 5 random numbers: {random_array}")

random_matrix = np.random.rand(3, 4) # Create a 2D array of shape (3,4)
print(f"2D array of shape (3,4):\n {random_matrix}")

# np.random.randn() Generates random numbers from a standard normal distribution (mean 0, standard deviation 1)
random_array = np.random.randn(5) # Create a 1D array of 5 random numbers from a standard normal distribution
print(f"1D array of 5 random numbers from a standard normal distribution: {random_array}")

random_matrix = np.random.randn(3, 4) # Create a 2D array of shape (3, 4)
print(f"2D array of shape (3,4): \n {random_matrix}")

# np.random.randint() - Generates random integers from a discrete uniform distribution between low (inclusive) and high (exclusive).
random_integers = np.random.randint(10, size=5)
print("Random Integers from 0-9:\n",random_integers)

random_matrix = np.random.randint(5, 15, size=(3, 4)) # Create a 2D array of shape (3, 4) with random integers between 5 and 1
print("2D array of shape (3, 4) with random integers between 5 and 1:\n",random_matrix)

# Random Sampling - np.random.choice: Generates a random sample from a given 1-D array.
sample = np.random.choice(arr, size=3, replace=False)
print("array with 3 random samples from `arr`, without replacement:\n",sample)


# Some not fun (read fun) exericise to do
# Create an array of 10 zeros.
# Create an array of 10 fives.
# Create a 3x3 matrix with values ranging from 0 to 8.
# Generate a random number between 0 and 1.

1D array of 5 random numbers: [0.86610505 0.29399289 0.77707068 0.19846089 0.25363272]
2D array of shape (3,4):
 [[0.02178846 0.2244907  0.2558271  0.02126902]
 [0.17588199 0.99090548 0.13413652 0.11572517]
 [0.90724097 0.36514636 0.71672129 0.29469358]]
1D array of 5 random numbers from a standard normal distribution: [0.15400014 0.57711182 0.37128358 0.24448178 0.55271372]
2D array of shape (3,4): 
 [[-0.82323302 -1.49901508  0.50033959  0.32763384]
 [ 0.20854871  0.91330976  1.2171602   0.93424435]
 [ 0.30492962  0.35940791 -0.97098128  1.15356543]]
Random Integers from 0-9:
 [0 0 5 1 1]
2D array of shape (3, 4) with random integers between 5 and 1:
 [[ 5  5  8  9]
 [ 7 12 14  5]
 [12 13  6  9]]
array with 3 random samples from `arr`, without replacement:
 [3.14159265 0.         1.57079633]


## Quering Dimensions

Querying dimensions in NumPy involves retrieving and understanding the structural attributes of an array, such as its number of dimensions, shape, and size. These properties are essential for understanding the layout of the data and for performing various operations that require knowledge of the array's structure.

Key Attributes for Querying Dimensions
1. Number of Dimensions - `ndim`
2. Shape - `shape`
3. Size -  `size`


### Number of Dimensions (`ndim`)

This attribute returns the number of dimensions (or axes) of the array.

In [7]:
import numpy as np

arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f"No. of Dimensions of arr_1d: {arr_1d.ndim}")  
print(f"No. of Dimensions of arr_2d: {arr_2d.ndim}")  
print(f"No. of Dimensions of arr_2d: {arr_3d.ndim}")  

No. of Dimensions of arr_1d: 1
No. of Dimensions of arr_2d: 2
No. of Dimensions of arr_2d: 3


### Shape (`shape`)

This attribute returns a tuple representing the dimensions of the array. Each element of the tuple represents the size of the array along that dimension.

In [8]:
print("Shape of arr_1d:", arr_1d.shape)
print("Shape of arr_2d:", arr_2d.shape)
print("Shape of arr_3d:", arr_3d.shape)

Shape of arr_1d: (3,)
Shape of arr_2d: (2, 3)
Shape of arr_3d: (2, 2, 3)


### Size (`size`)

This attribute returns the total number of elements in the array.

In [9]:
print("Size of arr_1d:", arr_1d.size)
print("Size of arr_2d:", arr_2d.size)
print("Size of arr_3d:", arr_3d.size)

Size of arr_1d: 3
Size of arr_2d: 6
Size of arr_3d: 12


Importance of Querying Dimensions
* Performing operations that require specific shapes.
* Debugging errors related to shape mismatches.
* Efficiently manipulating and transforming data.
* Ensuring compatibility with functions and methods that have shape requirements.

By querying the dimensions of an array, you gain insight into its structure, which helps you to write more effective and error-free code.

## Array Properties 

1. Data Type (`dtype`)
2. Item Size (`itemsize`)
3. Total Bytes (`nbytes`)
4. Transpose (`T`)
5. Flat Iterator (`Flat`)
6. Real and Imaginary Parts (`real` and `imag`)
7. Base (`base`)


### Data Type (`dtype`)

Returns the data type of the elements in the array. NumPy supports a variety of data types, including integers, floats, and more.

In [10]:
arr = np.array([[1, 2.5, 3], [4, 7, 6]])
print("Data type:", arr.dtype)

Data type: float64


### ItemItem Size (`itemsize`)

Returns the size (in bytes) of each element in the array.

In [11]:
print("Item size:", arr.itemsize)

Item size: 8


### Total Bytes (`nbytes`)

returns the total number of bytes consumed by the elements of the array. 

In [12]:
print("Total bytes:", arr.nbytes)

Total bytes: 48


### Transpose (`T`)

Returns the transpose of the array. For 2D arrays, it swaps the rows and columns.

In [13]:
print("Transpose:")
print(arr.T)

Transpose:
[[1.  4. ]
 [2.5 7. ]
 [3.  6. ]]


### Flat Iterator (`Flat`)

A flat iterator in NumPy is an object that allows you to iterate over the elements of a multi-dimensional array as if it were a one-dimensional array. It's essentially a way to flatten an array without actually creating a new array in memory, which can be more efficient.

In [14]:
print("Flat elements:")
for element in arr.flat:
    print(element, end=' ')

Flat elements:
1.0 2.5 3.0 4.0 7.0 6.0 

### Real and Imaginary Parts (`real` and `imag`)

Return the real and imaginary parts of the elements if the array contains complex numbers.

In [15]:
complex_arr = np.array([1+2j, 3+4j])
print("Real part: ",complex_arr.real)  
print("Complex part: ",complex_arr.imag)

Real part:  [1. 3.]
Complex part:  [2. 4.]


### Base (`base`)

In NumPy, the base attribute of an ndarray object provides information about the underlying memory structure of the array. Essentially, it tells you whether the array owns its data or shares it with another object.

When base is None<br>
* The array owns its data.
* No other object shares the same memory block.

When base is not None<br>
* The array is a view or slice of another array.
* The memory is shared with the base array.

In [16]:
original = np.array([1, 2, 3, 4])
print (original.base)

# slicing creates a view
view = original[1:3]
print(view.base is original)

None
True


## Array Operations

NumPy arrays support element-wise operations

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)    # Addition
print(arr1 - arr2)    # Subtraction
print(arr1 * arr2)    # Multiplication
print(arr1 / arr2)    # Division

print(arr1 > arr2)  
print(arr1 == arr2)  

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[False False False]
[False False False]


## Universal Functions (ufuncs)

* A universal function, or ufunc for short, is a function that operates on NumPy arrays element-wise. <br>
* This means it applies the function to each element of the array, producing a new array with the results.<br> 
* This is often referred to as "vectorization" and is a cornerstone of NumPy's performance.

In [18]:
#Basic Arithmetic Operations
print('Addition: ',np.add(arr1, arr2)) 
print('Substraction: ',np.subtract(arr1, arr2))  
print('Multiplication: ',np.multiply(arr1, arr2))  
print('Division: ',np.divide(arr1, arr2))


# Trignometric Functions
arr = np.array([0, np.pi/2, np.pi])

print('Sin of arr: ',np.sin(arr))  
print('Cos of arr: ',np.cos(arr))

# Exponential and Logarithmic Functions
print('Exponent: ',np.exp(arr1)) 
print('Log: ',np.log(arr1))

#Aggregate Functions
print('Sum: ',np.sum(arr1))  
print('Mean: ',np.mean(arr1))  
print('Std. Deviation:',np.std(arr1))
print('Square root: ',np.sqrt(arr1))

Addition:  [5 7 9]
Substraction:  [-3 -3 -3]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]
Sin of arr:  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos of arr:  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Exponent:  [ 2.71828183  7.3890561  20.08553692]
Log:  [0.         0.69314718 1.09861229]
Sum:  6
Mean:  2.0
Std. Deviation: 0.816496580927726
Square root:  [1.         1.41421356 1.73205081]


Difference between Array Operations and Universal Functions:<br><br>
`Array Operations `- Limited to basic arithmetic and logical operations (addition, subtraction, multiplication, division, comparisons).<br>
`Universal Functions ` - Covers a broader range of operations including mathematical, trigonometric, exponential, logarithmic, and aggregation functions.

## Array Manipulation

NumPy provides a rich set of functions for manipulating arrays.<br>
Some of them are:
1. Reshaping arrays: `Reshape`, `Resize`
2. Flattening arraya: `Flatten`, `Ravel`
3. Expanding and Squuezing dimensions: `np.expand_dims`, `np.squeeze`
4. Concatenation and stacking: `np.concatenate`, `np.vstack`, `np.hastack`, `np.stack`
5. Splitting array: `np.split`, `np.hsplit`, `np.vsplit` 

## Broadcasting

Broadcasting refers to the ability of the library to perform element-wise operations on arrays of different shapes. It allows NumPy to work with arrays of different dimensions in a way that the smaller array is virtually expanded to the size of the larger array without actually copying the data, thus making operations more efficient both in terms of memory and performance.

### Simpler Explanation 
Imagine you have a box of chocolates and you want to give each chocolate a wrapper.

One way: You could wrap each chocolate individually. This is like doing calculations in a regular programming loop, which can be slow. <br>
Another way: You have a big sheet of wrapping paper. You place the box of chocolates on the paper and cut out individual wrappers for each chocolate. This is like broadcasting in NumPy. <br>

Broadcasting is a clever way for NumPy to handle calculations with arrays of different sizes. Instead of doing calculations one by one (which is slow), it finds a way to "stretch" or "repeat" the smaller array to match the shape of the larger array. This lets NumPy perform calculations much faster.

Example:

* You have a list of numbers: [1, 2, 3]
* You want to add 5 to each number.
* Instead of adding 5 to each number individually, NumPy can "broadcast" the number 5 to match the shape of the list and add them together quickly.

### Rules of Broadcasting

1. Trailing Dimensions Match: When performing operations on two arrays, NumPy compares their shapes element-wise, starting from right and moving to left. Two dimensions are compatible if:

    * They are equal, or
    * One of them is 1.
    
2. Shape Expansion: If one of the arrays has fewer dimensions, its shape is padded with ones on its left side until both shapes have the same length.

![class 4](broadcasting_example.png)

In [26]:
# Example 1: Adding a Scalar to an Array

array = np.array([1, 2, 3])
scalar = 2
result = array + scalar
print("Broadcasting of a scalar to an array: ",result)
# the scalar `2` is broadcasted to the shape of the array [1, 2, 3]

# Example 2: Adding Two Arrays of Different Shapes
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([10, 20, 30])
result = array1 + array2
print("Broadcasting of two arrays of different shapes:",result)
# In this example, 'array2' is broadcasted to the shape of 'array1'.

# Example 3: Broadcasting with Different Number of Dimensions
array1 = np.array([[1], [2], [3]])
array2 = np.array([10, 20, 30])
result = array1 + array2
print("Braodcasting with different no. of dimensions: \n",result)
#Here, array1 has a shape of (3, 1) and array2 has a shape of (3,). 
#During the operation, array2 is broadcasted to shape (3, 3).


Broadcasting of a scalar to an array:  [3 4 5]
Broadcasting of two arrays of different shapes: [[11 22 33]
 [14 25 36]]
Braodcasting with different no. of dimensions: 
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


## Linear Algebra

NumPy provides a comprehensive suite of functions for performing linear algebra operations. Here, we'll cover some key operations, including matrix multiplication, calculating determinants, finding inverses, and solving linear equations.

### Matrix Multiplication 
Matrix multiplication is a fundamental operation in linear algebra. NumPy provides two ways to perform matrix multiplication: `np.dot` and the `@ operator`.

In [28]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result_dot = np.dot(A, B)
result_at = A @ B

print("Matrix multiplication using np.dot:")
print(result_dot)
print("\nMatrix multiplication using '@' operator:")
print(result_at)

Matrix multiplication using np.dot:
[[19 22]
 [43 50]]

Matrix multiplication using '@' operator:
[[19 22]
 [43 50]]


### Determinanat 
The determinant of a matrix is a scalar value that is a function of the entries of a square matrix. It can be used to determine whether a matrix is invertible.

`np.linalg.det`: This function computes the determinant of an array.


In [29]:
# Determinant
det_A = np.linalg.det(A)
print("\nDeterminant of A:")
print(det_A)

# what would be the determinant of the result of adding array A and B?


Determinant of A:
-2.0000000000000004


### Inverse

The inverse of a matrix A is the matrix A^-1 such that A * A^-1 = I, where I is the identity matrix.

`np.linalg.inv`: This function computes the (multiplicative) inverse of a matrix.

In [30]:
# Inverse
inv_A = np.linalg.inv(A)
print("\nInverse of A:")
print(inv_A)


Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


### Solving Linear Equations
To solve a system of linear equations of the form Ax = b,<br>
where A is a matrix and b is a vector, NumPy provides the np.linalg.solve function.

`np.linalg.solve` - This function solves the equation `Ax = b for x`.


![class 4](linear_eq.png)

In [31]:
# Solving linear equations from the above image
C = np.array([[3, 1], [1, 2]])
d = np.array([9, 8])
x = np.linalg.solve(C, d)
print("\nSolution of the system Ax = b:")
print(x)



Solution of the system Ax = b:
[2. 3.]


## Advanced Array Operations

NumPy provides a rich set of advanced array operations that allow for 
`sorting`, `finding unique elements` and `searching within arrays`

### Sorting
`np.sort` - Sorts an array along the specified axis. By default, it sorts along the last axis.


In [37]:
arr_2d = np.array([[3, 2, 1], [6, 5, 4]])
print("Array to be sorted:\n",arr_2d)
sorted_arr_2d = np.sort(arr_2d, axis=1)
print("Sorted array: \n",sorted_arr_2d)

Array to be sorted:
 [[3 2 1]
 [6 5 4]]
Sorted array: 
 [[1 2 3]
 [4 5 6]]


### Unique Elements

`np.unique` - Finds the unique elements of an array.

In [44]:
#arr = np.array([1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])
arr = ['s','s','t','t','t','w']

unique_elements, counts = np.unique(arr, return_counts=True)
print("Unique Elements: ",unique_elements)  
print("Counts: ",counts)

Unique Elements:  ['s' 't' 'w']
Counts:  [2 3 1]


### Searching 

`np.where` - Returns the indices of elements in an input array where a specified condition is `True`.<br>
`np.searchsorted` - Finds indices where elements should be inserted to maintain order.


In [46]:
# Example for np.where
arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr > 3)
print("\nIndices where arr > 3:")
print(indices)

# Example for np.searchsorted
sorted_arr = np.array([1, 3, 5, 7, 9])
print("Sorted array: \n",sorted_arr)
indices = np.searchsorted(sorted_arr, [2, 4, 6])
print("\nIndices where elements should be inserted to maintain order:")
print(indices)



Indices where arr > 3:
(array([3, 4]),)
Sorted array: 
 [1 3 5 7 9]

Indices where elements should be inserted to maintain order:
[1 2 3]
