# NumPy

NumPy (Numerical Python) is a library for the Python programming language that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [1]:
# To use numpy you need to install numpy library (if you don not have it in your system)
# you can do so by executing the below command

#pip install numpy

In [2]:
# To use NumPy in your Python program, you need to import it:
import numpy as np

## Core Concepts

### Arrays

* The core object in NumPy is the ndarray, which is a shorthand for "n-dimensional array".<br> 
* These arrays are faster and more efficient than Python lists for large datasets.



#### Creating Arrays

In [6]:
# you can create arrays in several ways
# From a List
arr = np.array([1,2,3,4,5])
print(f"Array from List: {arr}")

#From Nested Lists - 2d Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) 
print(f"Array 2d: {arr_2d}")

#From Built-in functions
zero = np.zeros((3, 3))        # Creates a 3x3 array filled with zeros
print(f"Array filled with zeros: {zero}")

ones = np.ones((2, 4))         # Creates a 2x4 array filled with ones
print(f"Array filled with ones: {ones}")

ex1 = np.arange(0, 10, 2)     # Creates an array with values from 0 to 10 with a step of 2
print(f"Array filled with values from 0 to 10 with step 2: {ex1}")

line = np.linspace(0, 1, 5)    # Creates an array with 5 values evenly spaced between 0 and 1
print(f"Array with 5 values evenly spaced between 0 and 1: {line}")


# Some not fun (read fun) exericise to do
# Create an array of 10 zeros.
# Create an array of 10 fives.
# Create a 3x3 matrix with values ranging from 0 to 8.
# Generate a random number between 0 and 1.

Array from List: [1 2 3 4 5]
Array 2d: [[1 2 3]
 [4 5 6]]
Array filled with zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array filled with ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array filled with values from 0 to 10 with step 2: [0 2 4 6 8]
Array with 5 values evenly spaced between 0 and 1: [0.   0.25 0.5  0.75 1.  ]
