# NumPy

NumPy (Numerical Python) is a library for the Python programming language that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [1]:
# To use numpy you need to install numpy library (if you don not have it in your system)
# you can do so by executing the below command

#pip install numpy

In [2]:
# To use NumPy in your Python program, you need to import it:
import numpy as np

## Arrays

* The core object in NumPy is the ndarray, which is a shorthand for "n-dimensional array".<br> 
* These arrays are faster and more efficient than Python lists for large datasets.



## Creating Arrays

In [12]:
# you can create arrays in several ways
# From a List
arr = np.array([1,2,3,4,5])
print(f"Array from List: {arr}")

#From Nested Lists - 2d Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) 
print(f"Array 2d: {arr_2d}")

#From Built-in functions
zero = np.zeros((3, 3))        # Creates a 3x3 array filled with zeros
print(f"Array filled with zeros: {zero}")

ones = np.ones((2, 4))         # Creates a 2x4 array filled with ones
print(f"Array filled with ones: {ones}")

ex1 = np.arange(0, 10, 2)     # Creates an array with values from 0 to 10 with a step of 2
print(f"Array filled with values from 0 to 10 with step 2: {ex1}")

line = np.linspace(0, 1, 5)    # Creates an array with 5 values evenly spaced between 0 and 1
print(f"Array with 5 values evenly spaced between 0 and 1: {line}")

# Using Random Functions

# np.random.rand() Generates random numbers from a uniform distribution between 0 and 1.
random_array = np.random.rand(5) # Create a 1D array of 5 random numbers
print(f": {random_array}")

random_matrix = np.random.rand(3, 4) # Create a 2D array of shape (3,
print(random_matrix)

# np.random.randn() Generates random numbers from a standard normal distribution (mean 0, standard deviation 1)
random_array = np.random.randn(5) # Create a 1D array of 5 random numbers from a standard normal distribution
print(random_array) 

random_matrix = np.random.randn(3, 4) # Create a 2D array of shape (3, 4)
print(random_matrix)

# np.random.randint() - Generates random integers from a discrete uniform distribution between low (inclusive) and high (exclusive).
random_integers = np.random.randint(10, size=5)
print(random_integers) #random_integers = np.random.randint(10, size=5)

random_matrix = np.random.randint(5, 15, size=(3, 4)) # Create a 2D array of shape (3, 4) with random integers between 5 and 1
print(random_matrix)


# Some not fun (read fun) exericise to do
# Create an array of 10 zeros.
# Create an array of 10 fives.
# Create a 3x3 matrix with values ranging from 0 to 8.
# Generate a random number between 0 and 1.

Array from List: [1 2 3 4 5]
Array 2d: [[1 2 3]
 [4 5 6]]
Array filled with zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array filled with ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array filled with values from 0 to 10 with step 2: [0 2 4 6 8]
Array with 5 values evenly spaced between 0 and 1: [0.   0.25 0.5  0.75 1.  ]
: [0.53598824 0.79526441 0.02125273 0.6865796  0.4199261 ]
[[0.98547623 0.1589288  0.2216515  0.08671912]
 [0.62487273 0.09680244 0.44485677 0.11876357]
 [0.71879801 0.93023377 0.3074137  0.45058102]]
[-2.52720269  1.1509127  -0.40557842 -0.79003604  1.32725241]
[[ 0.40676151  0.12509469  0.12669752  1.81500226]
 [ 0.47089211 -0.78048191 -0.03556349 -0.10080607]
 [-0.43593959 -1.19060818 -0.48545498 -0.31097757]]
[0 6 2 9 1]
[[ 8 14 10 13]
 [ 9 14 13  9]
 [ 9 14 10  8]]


## Quering Dimensions

Querying dimensions in NumPy involves retrieving and understanding the structural attributes of an array, such as its number of dimensions, shape, and size. These properties are essential for understanding the layout of the data and for performing various operations that require knowledge of the array's structure.

Key Attributes for Querying Dimensions
1. Number of Dimensions - `ndim`
2. Shape - `shape`
3. Size -  `size`


### Number of Dimensions (`ndim`)

This attribute returns the number of dimensions (or axes) of the array.

In [14]:
import numpy as np

arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f"No. of Dimensions of arr_1d: {arr_1d.ndim}")  
print(f"No. of Dimensions of arr_2d: {arr_2d.ndim}")  
print(f"No. of Dimensions of arr_2d: {arr_3d.ndim}")  

No. of Dimensions of arr_1d: 1
No. of Dimensions of arr_2d: 2
No. of Dimensions of arr_2d: 3


### Shape (`shape`)

This attribute returns a tuple representing the dimensions of the array. Each element of the tuple represents the size of the array along that dimension.

In [16]:
print("Shape of arr_1d:", arr_1d.shape)
print("Shape of arr_2d:", arr_2d.shape)
print("Shape of arr_3d:", arr_3d.shape)

Shape of arr_1d: (3,)
Shape of arr_2d: (2, 3)
Shape of arr_3d: (2, 2, 3)


### Size (`size`)

This attribute returns the total number of elements in the array.

In [17]:
print("Size of arr_1d:", arr_1d.size)
print("Size of arr_2d:", arr_2d.size)
print("Size of arr_3d:", arr_3d.size)

Size of arr_1d: 3
Size of arr_2d: 6
Size of arr_3d: 12


Importance of Querying Dimensions
* Performing operations that require specific shapes.
* Debugging errors related to shape mismatches.
* Efficiently manipulating and transforming data.
* Ensuring compatibility with functions and methods that have shape requirements.

By querying the dimensions of an array, you gain insight into its structure, which helps you to write more effective and error-free code.

## Array Properties 

## Array Operations

NumPy arrays support element-wise operations

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)    # Addition
print(arr1 - arr2)    # Subtraction
print(arr1 * arr2)    # Multiplication
print(arr1 / arr2)    # Division

print(arr1 > arr2)  
print(arr1 == arr2)  

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[False False False]
[False False False]


## Universal Functions (ufuncs)

* A universal function, or ufunc for short, is a function that operates on NumPy arrays element-wise. <br>
* This means it applies the function to each element of the array, producing a new array with the results.<br> 
* This is often referred to as "vectorization" and is a cornerstone of NumPy's performance.

In [10]:
#Basic Arithmetic Operations
print(np.add(arr1, arr2)) 
print(np.subtract(arr1, arr2))  
print(np.multiply(arr1, arr2))  
print(np.divide(arr1, arr2))


# Trignometric Functions
arr = np.array([0, np.pi/2, np.pi])

print(np.sin(arr))  
print(np.cos(arr))

# Exponential and Logarithmic Functions
print(np.exp(arr1)) 
print(np.log(arr1))

#Aggregate Functions
print(np.sum(arr1))  
print(np.mean(arr1))  
print(np.std(arr1))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
6
2.0
0.816496580927726


Difference between Array Operations and Universal Functions:<br><br>
`Array Operations `- Limited to basic arithmetic and logical operations (addition, subtraction, multiplication, division, comparisons).<br>
`Universal Functions ` - Covers a broader range of operations including mathematical, trigonometric, exponential, logarithmic, and aggregation functions.